/* GENERATED by scripts/design/upload_world3d_to_r2.mjs — 手編集禁止。
   データの正は本体 repo の assets/mock（.claude/rules/mock-data.md）。
   circles=18 places=8 posts=60（中心から 2km 以内） */
window.World3DData = {
  "center": {
    "lat": 35.65905,
    "lng": 139.70064
  },
  "focus": {
    "id": "circle-01",
    "lat": 35.65905,
    "lng": 139.70064,
    "radiusMeters": 500,
    "label": "サークル渋谷"
  },
  "circles": [
    {
      "id": "circle-01",
      "lat": 35.65905,
      "lng": 139.70064,
      "radiusMeters": 500,
      "label": "サークル渋谷"
    },
    {
      "id": "circle-02",
      "lat": 35.66075,
      "lng": 139.70225,
      "radiusMeters": 500,
      "label": "サークル神宮前"
    },
    {
      "id": "circle-03",
      "lat": 35.66305,
      "lng": 139.69564,
      "radiusMeters": 500,
      "label": "サークル代々木"
    },
    {
      "id": "circle-04",
      "lat": 35.6896,
      "lng": 139.7005,
      "radiusMeters": 800,
      "label": "サークル新宿"
    },
    {
      "id": "circle-05",
      "lat": 35.6573,
      "lng": 139.6979,
      "radiusMeters": 500,
      "label": "サークル道玄坂"
    },
    {
      "id": "circle-06",
      "lat": 35.6602,
      "lng": 139.7028,
      "radiusMeters": 500,
      "label": "サークル宮益坂"
    },
    {
      "id": "circle-07",
      "lat": 35.6702,
      "lng": 139.7027,
      "radiusMeters": 600,
      "label": "サークル原宿"
    },
    {
      "id": "circle-08",
      "lat": 35.6652,
      "lng": 139.7124,
      "radiusMeters": 600,
      "label": "サークル表参道"
    },
    {
      "id": "circle-09",
      "lat": 35.6467,
      "lng": 139.71,
      "radiusMeters": 500,
      "label": "サークル恵比寿"
    },
    {
      "id": "circle-10",
      "lat": 35.644,
      "lng": 139.6985,
      "radiusMeters": 500,
      "label": "サークル中目黒"
    },
    {
      "id": "circle-11",
      "lat": 35.6614,
      "lng": 139.6993,
      "radiusMeters": 500,
      "label": "Ranway Shibuya"
    },
    {
      "id": "circle-12",
      "lat": 35.6577,
      "lng": 139.7024,
      "radiusMeters": 500,
      "label": "GrafitiMan Circle"
    },
    {
      "id": "circle-13",
      "lat": 35.6608,
      "lng": 139.6986,
      "radiusMeters": 500,
      "label": "Shokugeki no Shibuya"
    },
    {
      "id": "circle-14",
      "lat": 35.6647,
      "lng": 139.6968,
      "radiusMeters": 500,
      "label": "Shibuya Skateboard Park"
    },
    {
      "id": "circle-15",
      "lat": 35.6589,
      "lng": 139.7043,
      "radiusMeters": 500,
      "label": "Shibuya Dance"
    },
    {
      "id": "circle-16",
      "lat": 35.4437,
      "lng": 139.638,
      "radiusMeters": 500,
      "label": "サークル横浜"
    },
    {
      "id": "circle-17",
      "lat": 34.7025,
      "lng": 135.4959,
      "radiusMeters": 500,
      "label": "サークル大阪"
    },
    {
      "id": "circle-18",
      "lat": 35.0116,
      "lng": 135.7681,
      "radiusMeters": 500,
      "label": "サークル京都"
    }
  ],
  "places": [
    {
      "key": "f_60188ca900bed58b_9afa368e452f3281",
      "lat": 35.66175,
      "lng": 139.69805,
      "name": "TK NIGHTCLUB",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel038.jpg"
    },
    {
      "key": "f_60188b58f2d8a5b3_47a1a5f3a1a0c8c3",
      "lat": 35.6576,
      "lng": 139.6961,
      "name": "WOMB",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel021.jpg"
    },
    {
      "key": "f_mock_camelot",
      "lat": 35.6593,
      "lng": 139.6968,
      "name": "CLUB CAMELOT",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel030.jpg"
    },
    {
      "key": "f_mock_nonbei",
      "lat": 35.6605,
      "lng": 139.7025,
      "name": "のんべい横丁",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel012.jpg"
    },
    {
      "key": "f_mock_miyashita",
      "lat": 35.6614,
      "lng": 139.7027,
      "name": "MIYASHITA PARK",
      "imageUrl": "https://media.toopdbq.com/mock/sample/models/real-05.jpg"
    },
    {
      "key": "f_mock_bunkamura",
      "lat": 35.6588,
      "lng": 139.6952,
      "name": "Bunkamura",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel038.jpg"
    },
    {
      "key": "f_mock_catstreet",
      "lat": 35.6636,
      "lng": 139.7053,
      "name": "キャットストリート",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel036.jpg"
    },
    {
      "key": "f_mock_hikarie",
      "lat": 35.659,
      "lng": 139.7036,
      "name": "渋谷ヒカリエ",
      "imageUrl": "https://media.toopdbq.com/mock/sample/reel/reel047.jpg"
    }
  ],
  "posts": [
    {
      "id": "real-10",
      "lat": 35.659,
      "lng": 139.7009,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-10.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/models/real-10.glb",
      "videoUrl": null
    },
    {
      "id": "demo_quest_01",
      "lat": 35.6595,
      "lng": 139.7005,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-06.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "demo_quest_taro",
      "lat": 35.6592,
      "lng": 139.7012,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-01.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "demo_feed-01",
      "lat": 35.6592,
      "lng": 139.7012,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-03.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "demo_feed-02",
      "lat": 35.6592,
      "lng": 139.7012,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-05.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "demo_feed-03",
      "lat": 35.6592,
      "lng": 139.7012,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-07.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-065",
      "lat": 35.658614,
      "lng": 139.701058,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel001.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-088",
      "lat": 35.659257,
      "lng": 139.699813,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel027.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-075",
      "lat": 35.65844,
      "lng": 139.70132,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel006.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-111",
      "lat": 35.659431,
      "lng": 139.701579,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel058.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-046",
      "lat": 35.658158,
      "lng": 139.700529,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel058.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-057",
      "lat": 35.65985,
      "lng": 139.701232,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel010.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "mqmav1c7_wnam",
      "lat": 35.65975,
      "lng": 139.6998,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmav1c7_wnam/thumbnail.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmav1c7_wnam/model.glb",
      "videoUrl": "https://media.toopdbq.com/mock/sample/3d/mqmav1c7_wnam/video.mp4"
    },
    {
      "id": "real-09",
      "lat": 35.65977,
      "lng": 139.70153,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-09.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/models/real-09.glb",
      "videoUrl": null
    },
    {
      "id": "gen-022",
      "lat": 35.658026,
      "lng": 139.700898,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel020.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-076",
      "lat": 35.660166,
      "lng": 139.700461,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel012.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-100",
      "lat": 35.657899,
      "lng": 139.701416,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel046.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-115",
      "lat": 35.659726,
      "lng": 139.699148,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel021.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-013",
      "lat": 35.657573,
      "lng": 139.700565,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel022.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-020",
      "lat": 35.660352,
      "lng": 139.699299,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel011.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-033",
      "lat": 35.659271,
      "lng": 139.70279,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel032.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-064",
      "lat": 35.660886,
      "lng": 139.701266,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel054.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-12-01",
      "lat": 35.6577,
      "lng": 139.7024,
      "circleId": "circle-12",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel013.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-12-02",
      "lat": 35.6577,
      "lng": 139.7024,
      "circleId": "circle-12",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel015.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-12-03",
      "lat": 35.6577,
      "lng": 139.7024,
      "circleId": "circle-12",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel017.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-12-04",
      "lat": 35.6577,
      "lng": 139.7024,
      "circleId": "circle-12",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel020.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-024",
      "lat": 35.658194,
      "lng": 139.702893,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel034.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-108",
      "lat": 35.661056,
      "lng": 139.700204,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel037.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-120",
      "lat": 35.659195,
      "lng": 139.703202,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel056.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "mqmbpk42_d6sz",
      "lat": 35.6602,
      "lng": 139.7028,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpk42_d6sz/thumbnail.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpk42_d6sz/model.glb",
      "videoUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpk42_d6sz/video.mp4"
    },
    {
      "id": "demo_quest_taro06",
      "lat": 35.6602,
      "lng": 139.7028,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/models/real-04.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "mqmaxkwz_tkvb",
      "lat": 35.66075,
      "lng": 139.70225,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmaxkwz_tkvb/thumbnail.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmaxkwz_tkvb/model.glb",
      "videoUrl": null
    },
    {
      "id": "gen-077",
      "lat": 35.658951,
      "lng": 139.697921,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel015.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-041",
      "lat": 35.661183,
      "lng": 139.70162,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel023.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-017",
      "lat": 35.660894,
      "lng": 139.698954,
      "circleId": "circle-06",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel050.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-072",
      "lat": 35.659512,
      "lng": 139.697849,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel045.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-13-01",
      "lat": 35.6608,
      "lng": 139.6986,
      "circleId": "circle-13",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel023.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-13-02",
      "lat": 35.6608,
      "lng": 139.6986,
      "circleId": "circle-13",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel026.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-13-03",
      "lat": 35.6608,
      "lng": 139.6986,
      "circleId": "circle-13",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel029.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-13-04",
      "lat": 35.6608,
      "lng": 139.6986,
      "circleId": "circle-13",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel032.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-13-05",
      "lat": 35.6608,
      "lng": 139.6986,
      "circleId": "circle-13",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel035.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-112",
      "lat": 35.660994,
      "lng": 139.698588,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel005.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-11-01",
      "lat": 35.6614,
      "lng": 139.6993,
      "circleId": "circle-11",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel001.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-11-02",
      "lat": 35.6614,
      "lng": 139.6993,
      "circleId": "circle-11",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel004.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-11-03",
      "lat": 35.6614,
      "lng": 139.6993,
      "circleId": "circle-11",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel007.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-11-04",
      "lat": 35.6614,
      "lng": 139.6993,
      "circleId": "circle-11",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel010.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-11-05",
      "lat": 35.6614,
      "lng": 139.6993,
      "circleId": "circle-11",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel012.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-106",
      "lat": 35.657342,
      "lng": 139.698257,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel023.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-051",
      "lat": 35.657416,
      "lng": 139.703116,
      "circleId": "circle-02",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel028.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-037",
      "lat": 35.658074,
      "lng": 139.69764,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel060.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-081",
      "lat": 35.656909,
      "lng": 139.698719,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel043.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "mqmbpeas_f3co",
      "lat": 35.6573,
      "lng": 139.6979,
      "circleId": "circle-05",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpeas_f3co/thumbnail.jpg",
      "glbUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpeas_f3co/model.glb",
      "videoUrl": "https://media.toopdbq.com/mock/sample/3d/mqmbpeas_f3co/video.mp4"
    },
    {
      "id": "gen-105",
      "lat": 35.658559,
      "lng": 139.704076,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel016.png",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-15-01",
      "lat": 35.6589,
      "lng": 139.7043,
      "circleId": "circle-15",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel050.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-15-02",
      "lat": 35.6589,
      "lng": 139.7043,
      "circleId": "circle-15",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel053.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-15-03",
      "lat": 35.6589,
      "lng": 139.7043,
      "circleId": "circle-15",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel056.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-15-04",
      "lat": 35.6589,
      "lng": 139.7043,
      "circleId": "circle-15",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel059.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "reco-15-05",
      "lat": 35.6589,
      "lng": 139.7043,
      "circleId": "circle-15",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel002.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-006",
      "lat": 35.658269,
      "lng": 139.697052,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel038.jpg",
      "glbUrl": null,
      "videoUrl": null
    },
    {
      "id": "gen-117",
      "lat": 35.661123,
      "lng": 139.703472,
      "circleId": "circle-01",
      "thumbUrl": "https://media.toopdbq.com/mock/sample/reel/reel035.jpg",
      "glbUrl": null,
      "videoUrl": null
    }
  ],
  "quest": {
    "id": "circle-01_20260731",
    "title": "とぅーぷどぅっくバーで乾杯",
    "endMs": 1785510000000
  }
};
